 //------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosArsi.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/AdministraDatos")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioEntity", Namespace="http://schemas.datacontract.org/2004/07/LibreriasMercado.Entidades")]
    [System.SerializableAttribute()]
    public partial class UsuarioEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string calleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coloniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string municipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoWhatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string calle {
            get {
                return this.calleField;
            }
            set {
                if ((object.ReferenceEquals(this.calleField, value) != true)) {
                    this.calleField = value;
                    this.RaisePropertyChanged("calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                if ((object.ReferenceEquals(this.coloniaField, value) != true)) {
                    this.coloniaField = value;
                    this.RaisePropertyChanged("colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cp {
            get {
                return this.cpField;
            }
            set {
                if ((object.ReferenceEquals(this.cpField, value) != true)) {
                    this.cpField = value;
                    this.RaisePropertyChanged("cp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eMail {
            get {
                return this.eMailField;
            }
            set {
                if ((object.ReferenceEquals(this.eMailField, value) != true)) {
                    this.eMailField = value;
                    this.RaisePropertyChanged("eMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                if ((object.ReferenceEquals(this.estatusField, value) != true)) {
                    this.estatusField = value;
                    this.RaisePropertyChanged("estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((this.idClienteField.Equals(value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                if ((object.ReferenceEquals(this.municipioField, value) != true)) {
                    this.municipioField = value;
                    this.RaisePropertyChanged("municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroExt {
            get {
                return this.numeroExtField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroExtField, value) != true)) {
                    this.numeroExtField = value;
                    this.RaisePropertyChanged("numeroExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroInt {
            get {
                return this.numeroIntField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroIntField, value) != true)) {
                    this.numeroIntField = value;
                    this.RaisePropertyChanged("numeroInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefonoContacto {
            get {
                return this.telefonoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoContactoField, value) != true)) {
                    this.telefonoContactoField = value;
                    this.RaisePropertyChanged("telefonoContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefonoWhats {
            get {
                return this.telefonoWhatsField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoWhatsField, value) != true)) {
                    this.telefonoWhatsField = value;
                    this.RaisePropertyChanged("telefonoWhats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaEntity", Namespace="http://schemas.datacontract.org/2004/07/LibreriasMercado.Entidades")]
    [System.SerializableAttribute()]
    public partial class EmpresaEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumEmpleadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float VentasAnualesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string calleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coloniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eMailCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string municipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoWhatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicioOperacion {
            get {
                return this.FechaInicioOperacionField;
            }
            set {
                if ((this.FechaInicioOperacionField.Equals(value) != true)) {
                    this.FechaInicioOperacionField = value;
                    this.RaisePropertyChanged("FechaInicioOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpresa {
            get {
                return this.IdEmpresaField;
            }
            set {
                if ((this.IdEmpresaField.Equals(value) != true)) {
                    this.IdEmpresaField = value;
                    this.RaisePropertyChanged("IdEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoEmpresa {
            get {
                return this.IdTipoEmpresaField;
            }
            set {
                if ((this.IdTipoEmpresaField.Equals(value) != true)) {
                    this.IdTipoEmpresaField = value;
                    this.RaisePropertyChanged("IdTipoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreContacto {
            get {
                return this.NombreContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreContactoField, value) != true)) {
                    this.NombreContactoField = value;
                    this.RaisePropertyChanged("NombreContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpresa {
            get {
                return this.NombreEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpresaField, value) != true)) {
                    this.NombreEmpresaField = value;
                    this.RaisePropertyChanged("NombreEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumEmpleados {
            get {
                return this.NumEmpleadosField;
            }
            set {
                if ((this.NumEmpleadosField.Equals(value) != true)) {
                    this.NumEmpleadosField = value;
                    this.RaisePropertyChanged("NumEmpleados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puesto {
            get {
                return this.PuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.PuestoField, value) != true)) {
                    this.PuestoField = value;
                    this.RaisePropertyChanged("Puesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float VentasAnuales {
            get {
                return this.VentasAnualesField;
            }
            set {
                if ((this.VentasAnualesField.Equals(value) != true)) {
                    this.VentasAnualesField = value;
                    this.RaisePropertyChanged("VentasAnuales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string calle {
            get {
                return this.calleField;
            }
            set {
                if ((object.ReferenceEquals(this.calleField, value) != true)) {
                    this.calleField = value;
                    this.RaisePropertyChanged("calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                if ((object.ReferenceEquals(this.coloniaField, value) != true)) {
                    this.coloniaField = value;
                    this.RaisePropertyChanged("colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenaC {
            get {
                return this.contrasenaCField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaCField, value) != true)) {
                    this.contrasenaCField = value;
                    this.RaisePropertyChanged("contrasenaC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cp {
            get {
                return this.cpField;
            }
            set {
                if ((object.ReferenceEquals(this.cpField, value) != true)) {
                    this.cpField = value;
                    this.RaisePropertyChanged("cp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eMail {
            get {
                return this.eMailField;
            }
            set {
                if ((object.ReferenceEquals(this.eMailField, value) != true)) {
                    this.eMailField = value;
                    this.RaisePropertyChanged("eMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eMailC {
            get {
                return this.eMailCField;
            }
            set {
                if ((object.ReferenceEquals(this.eMailCField, value) != true)) {
                    this.eMailCField = value;
                    this.RaisePropertyChanged("eMailC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                if ((object.ReferenceEquals(this.estatusField, value) != true)) {
                    this.estatusField = value;
                    this.RaisePropertyChanged("estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                if ((object.ReferenceEquals(this.municipioField, value) != true)) {
                    this.municipioField = value;
                    this.RaisePropertyChanged("municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroExt {
            get {
                return this.numeroExtField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroExtField, value) != true)) {
                    this.numeroExtField = value;
                    this.RaisePropertyChanged("numeroExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroInt {
            get {
                return this.numeroIntField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroIntField, value) != true)) {
                    this.numeroIntField = value;
                    this.RaisePropertyChanged("numeroInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefonoContacto {
            get {
                return this.telefonoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoContactoField, value) != true)) {
                    this.telefonoContactoField = value;
                    this.RaisePropertyChanged("telefonoContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefonoWhats {
            get {
                return this.telefonoWhatsField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoWhatsField, value) != true)) {
                    this.telefonoWhatsField = value;
                    this.RaisePropertyChanged("telefonoWhats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoEntity", Namespace="http://schemas.datacontract.org/2004/07/LibreriasMercado.Entidades")]
    [System.SerializableAttribute()]
    public partial class ProductoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTiendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TiendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipo_cursoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenido {
            get {
                return this.ContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenidoField, value) != true)) {
                    this.ContenidoField = value;
                    this.RaisePropertyChanged("Contenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((this.IdCategoriaField.Equals(value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTienda {
            get {
                return this.IdTiendaField;
            }
            set {
                if ((this.IdTiendaField.Equals(value) != true)) {
                    this.IdTiendaField = value;
                    this.RaisePropertyChanged("IdTienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tienda {
            get {
                return this.TiendaField;
            }
            set {
                if ((object.ReferenceEquals(this.TiendaField, value) != true)) {
                    this.TiendaField = value;
                    this.RaisePropertyChanged("Tienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPC {
            get {
                return this.UPCField;
            }
            set {
                if ((object.ReferenceEquals(this.UPCField, value) != true)) {
                    this.UPCField = value;
                    this.RaisePropertyChanged("UPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo_curso {
            get {
                return this.tipo_cursoField;
            }
            set {
                if ((this.tipo_cursoField.Equals(value) != true)) {
                    this.tipo_cursoField = value;
                    this.RaisePropertyChanged("tipo_curso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarritoEntity", Namespace="http://schemas.datacontract.org/2004/07/LibreriasMercado.Entidades")]
    [System.SerializableAttribute()]
    public partial class CarritoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionProdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTiendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreTiendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionProd {
            get {
                return this.DescripcionProdField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionProdField, value) != true)) {
                    this.DescripcionProdField = value;
                    this.RaisePropertyChanged("DescripcionProd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTienda {
            get {
                return this.IdTiendaField;
            }
            set {
                if ((this.IdTiendaField.Equals(value) != true)) {
                    this.IdTiendaField = value;
                    this.RaisePropertyChanged("IdTienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTienda {
            get {
                return this.NombreTiendaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreTiendaField, value) != true)) {
                    this.NombreTiendaField = value;
                    this.RaisePropertyChanged("NombreTienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DireccionEntity", Namespace="http://schemas.datacontract.org/2004/07/LibreriasMercado.Entidades")]
    [System.SerializableAttribute()]
    public partial class DireccionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idMunicipioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia {
            get {
                return this.ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoniaField, value) != true)) {
                    this.ColoniaField = value;
                    this.RaisePropertyChanged("Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipio {
            get {
                return this.MunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioField, value) != true)) {
                    this.MunicipioField = value;
                    this.RaisePropertyChanged("Municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idColonia {
            get {
                return this.idColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.idColoniaField, value) != true)) {
                    this.idColoniaField = value;
                    this.RaisePropertyChanged("idColonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.idEstadoField, value) != true)) {
                    this.idEstadoField = value;
                    this.RaisePropertyChanged("idEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMunicipio {
            get {
                return this.idMunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.idMunicipioField, value) != true)) {
                    this.idMunicipioField = value;
                    this.RaisePropertyChanged("idMunicipio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaEntity", Namespace="http://schemas.datacontract.org/2004/07/LibreriasMercado.Entidades")]
    [System.SerializableAttribute()]
    public partial class CategoriaEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionCategoria {
            get {
                return this.descripcionCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionCategoriaField, value) != true)) {
                    this.descripcionCategoriaField = value;
                    this.RaisePropertyChanged("descripcionCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoriaProducto {
            get {
                return this.idCategoriaProductoField;
            }
            set {
                if ((this.idCategoriaProductoField.Equals(value) != true)) {
                    this.idCategoriaProductoField = value;
                    this.RaisePropertyChanged("idCategoriaProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.ISAdmDatos")]
    public interface ISAdmDatos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISAdmDatos/GetDataUsingDataContractResponse")]
        CursosArsi.WebService.CompositeType GetDataUsingDataContract(CursosArsi.WebService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISAdmDatos/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<CursosArsi.WebService.CompositeType> GetDataUsingDataContractAsync(CursosArsi.WebService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRegisterUser", ReplyAction="http://tempuri.org/ISAdmDatos/SetRegisterUserResponse")]
        string SetRegisterUser(CursosArsi.WebService.UsuarioEntity user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRegisterUser", ReplyAction="http://tempuri.org/ISAdmDatos/SetRegisterUserResponse")]
        System.Threading.Tasks.Task<string> SetRegisterUserAsync(CursosArsi.WebService.UsuarioEntity user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRegisterEmpresa", ReplyAction="http://tempuri.org/ISAdmDatos/SetRegisterEmpresaResponse")]
        string SetRegisterEmpresa(CursosArsi.WebService.EmpresaEntity user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRegisterEmpresa", ReplyAction="http://tempuri.org/ISAdmDatos/SetRegisterEmpresaResponse")]
        System.Threading.Tasks.Task<string> SetRegisterEmpresaAsync(CursosArsi.WebService.EmpresaEntity user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRegisterUserApp", ReplyAction="http://tempuri.org/ISAdmDatos/SetRegisterUserAppResponse")]
        string SetRegisterUserApp(CursosArsi.WebService.UsuarioEntity user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRegisterUserApp", ReplyAction="http://tempuri.org/ISAdmDatos/SetRegisterUserAppResponse")]
        System.Threading.Tasks.Task<string> SetRegisterUserAppAsync(CursosArsi.WebService.UsuarioEntity user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetProductos", ReplyAction="http://tempuri.org/ISAdmDatos/GetProductosResponse")]
        CursosArsi.WebService.ProductoEntity[] GetProductos(string cadena, string cp, int idTienda, int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetProductos", ReplyAction="http://tempuri.org/ISAdmDatos/GetProductosResponse")]
        System.Threading.Tasks.Task<CursosArsi.WebService.ProductoEntity[]> GetProductosAsync(string cadena, string cp, int idTienda, int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetProductosCategoria", ReplyAction="http://tempuri.org/ISAdmDatos/GetProductosCategoriaResponse")]
        CursosArsi.WebService.ProductoEntity[] GetProductosCategoria(string cadena, int idCategoria, int idTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetProductosCategoria", ReplyAction="http://tempuri.org/ISAdmDatos/GetProductosCategoriaResponse")]
        System.Threading.Tasks.Task<CursosArsi.WebService.ProductoEntity[]> GetProductosCategoriaAsync(string cadena, int idCategoria, int idTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetNumeroProductos", ReplyAction="http://tempuri.org/ISAdmDatos/GetNumeroProductosResponse")]
        int GetNumeroProductos(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetNumeroProductos", ReplyAction="http://tempuri.org/ISAdmDatos/GetNumeroProductosResponse")]
        System.Threading.Tasks.Task<int> GetNumeroProductosAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetCarrito", ReplyAction="http://tempuri.org/ISAdmDatos/GetCarritoResponse")]
        CursosArsi.WebService.ProductoEntity[] GetCarrito(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetCarrito", ReplyAction="http://tempuri.org/ISAdmDatos/GetCarritoResponse")]
        System.Threading.Tasks.Task<CursosArsi.WebService.ProductoEntity[]> GetCarritoAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRegistraPedidoApp", ReplyAction="http://tempuri.org/ISAdmDatos/SetRegistraPedidoAppResponse")]
        int SetRegistraPedidoApp(CursosArsi.WebService.CarritoEntity[] carritoApp, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRegistraPedidoApp", ReplyAction="http://tempuri.org/ISAdmDatos/SetRegistraPedidoAppResponse")]
        System.Threading.Tasks.Task<int> SetRegistraPedidoAppAsync(CursosArsi.WebService.CarritoEntity[] carritoApp, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetValidaUsuario", ReplyAction="http://tempuri.org/ISAdmDatos/GetValidaUsuarioResponse")]
        CursosArsi.WebService.UsuarioEntity GetValidaUsuario(string usuario, string passw, bool encriptado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetValidaUsuario", ReplyAction="http://tempuri.org/ISAdmDatos/GetValidaUsuarioResponse")]
        System.Threading.Tasks.Task<CursosArsi.WebService.UsuarioEntity> GetValidaUsuarioAsync(string usuario, string passw, bool encriptado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetConfirmaUsuario", ReplyAction="http://tempuri.org/ISAdmDatos/GetConfirmaUsuarioResponse")]
        CursosArsi.WebService.UsuarioEntity GetConfirmaUsuario(string usuario, string passw, bool encriptado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetConfirmaUsuario", ReplyAction="http://tempuri.org/ISAdmDatos/GetConfirmaUsuarioResponse")]
        System.Threading.Tasks.Task<CursosArsi.WebService.UsuarioEntity> GetConfirmaUsuarioAsync(string usuario, string passw, bool encriptado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetDatosDireccion", ReplyAction="http://tempuri.org/ISAdmDatos/GetDatosDireccionResponse")]
        CursosArsi.WebService.DireccionEntity GetDatosDireccion(string codigoPostal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetDatosDireccion", ReplyAction="http://tempuri.org/ISAdmDatos/GetDatosDireccionResponse")]
        System.Threading.Tasks.Task<CursosArsi.WebService.DireccionEntity> GetDatosDireccionAsync(string codigoPostal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetCambiaPassword", ReplyAction="http://tempuri.org/ISAdmDatos/SetCambiaPasswordResponse")]
        string SetCambiaPassword(int idUsuario, string nvoPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetCambiaPassword", ReplyAction="http://tempuri.org/ISAdmDatos/SetCambiaPasswordResponse")]
        System.Threading.Tasks.Task<string> SetCambiaPasswordAsync(int idUsuario, string nvoPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRecuperaPassword", ReplyAction="http://tempuri.org/ISAdmDatos/SetRecuperaPasswordResponse")]
        string SetRecuperaPassword(string eMail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRecuperaPassword", ReplyAction="http://tempuri.org/ISAdmDatos/SetRecuperaPasswordResponse")]
        System.Threading.Tasks.Task<string> SetRecuperaPasswordAsync(string eMail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetListaCategorias", ReplyAction="http://tempuri.org/ISAdmDatos/GetListaCategoriasResponse")]
        CursosArsi.WebService.CategoriaEntity[] GetListaCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetListaCategorias", ReplyAction="http://tempuri.org/ISAdmDatos/GetListaCategoriasResponse")]
        System.Threading.Tasks.Task<CursosArsi.WebService.CategoriaEntity[]> GetListaCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetListaCategoriasEmpresa", ReplyAction="http://tempuri.org/ISAdmDatos/GetListaCategoriasEmpresaResponse")]
        CursosArsi.WebService.CategoriaEntity[] GetListaCategoriasEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/GetListaCategoriasEmpresa", ReplyAction="http://tempuri.org/ISAdmDatos/GetListaCategoriasEmpresaResponse")]
        System.Threading.Tasks.Task<CursosArsi.WebService.CategoriaEntity[]> GetListaCategoriasEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRegistraProductoApp", ReplyAction="http://tempuri.org/ISAdmDatos/SetRegistraProductoAppResponse")]
        bool SetRegistraProductoApp(CursosArsi.WebService.ProductoEntity producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAdmDatos/SetRegistraProductoApp", ReplyAction="http://tempuri.org/ISAdmDatos/SetRegistraProductoAppResponse")]
        System.Threading.Tasks.Task<bool> SetRegistraProductoAppAsync(CursosArsi.WebService.ProductoEntity producto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISAdmDatosChannel : CursosArsi.WebService.ISAdmDatos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAdmDatosClient : System.ServiceModel.ClientBase<CursosArsi.WebService.ISAdmDatos>, CursosArsi.WebService.ISAdmDatos {
        
        public SAdmDatosClient() {
        }
        
        public SAdmDatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAdmDatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAdmDatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAdmDatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CursosArsi.WebService.CompositeType GetDataUsingDataContract(CursosArsi.WebService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<CursosArsi.WebService.CompositeType> GetDataUsingDataContractAsync(CursosArsi.WebService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string SetRegisterUser(CursosArsi.WebService.UsuarioEntity user) {
            return base.Channel.SetRegisterUser(user);
        }
        
        public System.Threading.Tasks.Task<string> SetRegisterUserAsync(CursosArsi.WebService.UsuarioEntity user) {
            return base.Channel.SetRegisterUserAsync(user);
        }
        
        public string SetRegisterEmpresa(CursosArsi.WebService.EmpresaEntity user) {
            return base.Channel.SetRegisterEmpresa(user);
        }
        
        public System.Threading.Tasks.Task<string> SetRegisterEmpresaAsync(CursosArsi.WebService.EmpresaEntity user) {
            return base.Channel.SetRegisterEmpresaAsync(user);
        }
        
        public string SetRegisterUserApp(CursosArsi.WebService.UsuarioEntity user) {
            return base.Channel.SetRegisterUserApp(user);
        }
        
        public System.Threading.Tasks.Task<string> SetRegisterUserAppAsync(CursosArsi.WebService.UsuarioEntity user) {
            return base.Channel.SetRegisterUserAppAsync(user);
        }
        
        public CursosArsi.WebService.ProductoEntity[] GetProductos(string cadena, string cp, int idTienda, int idCliente) {
            return base.Channel.GetProductos(cadena, cp, idTienda, idCliente);
        }
        
        public System.Threading.Tasks.Task<CursosArsi.WebService.ProductoEntity[]> GetProductosAsync(string cadena, string cp, int idTienda, int idCliente) {
            return base.Channel.GetProductosAsync(cadena, cp, idTienda, idCliente);
        }
        
        public CursosArsi.WebService.ProductoEntity[] GetProductosCategoria(string cadena, int idCategoria, int idTienda) {
            return base.Channel.GetProductosCategoria(cadena, idCategoria, idTienda);
        }
        
        public System.Threading.Tasks.Task<CursosArsi.WebService.ProductoEntity[]> GetProductosCategoriaAsync(string cadena, int idCategoria, int idTienda) {
            return base.Channel.GetProductosCategoriaAsync(cadena, idCategoria, idTienda);
        }
        
        public int GetNumeroProductos(int idUsuario) {
            return base.Channel.GetNumeroProductos(idUsuario);
        }
        
        public System.Threading.Tasks.Task<int> GetNumeroProductosAsync(int idUsuario) {
            return base.Channel.GetNumeroProductosAsync(idUsuario);
        }
        
        public CursosArsi.WebService.ProductoEntity[] GetCarrito(int idUsuario) {
            return base.Channel.GetCarrito(idUsuario);
        }
        
        public System.Threading.Tasks.Task<CursosArsi.WebService.ProductoEntity[]> GetCarritoAsync(int idUsuario) {
            return base.Channel.GetCarritoAsync(idUsuario);
        }
        
        public int SetRegistraPedidoApp(CursosArsi.WebService.CarritoEntity[] carritoApp, int idUsuario) {
            return base.Channel.SetRegistraPedidoApp(carritoApp, idUsuario);
        }
        
        public System.Threading.Tasks.Task<int> SetRegistraPedidoAppAsync(CursosArsi.WebService.CarritoEntity[] carritoApp, int idUsuario) {
            return base.Channel.SetRegistraPedidoAppAsync(carritoApp, idUsuario);
        }
        
        public CursosArsi.WebService.UsuarioEntity GetValidaUsuario(string usuario, string passw, bool encriptado) {
            return base.Channel.GetValidaUsuario(usuario, passw, encriptado);
        }
        
        public System.Threading.Tasks.Task<CursosArsi.WebService.UsuarioEntity> GetValidaUsuarioAsync(string usuario, string passw, bool encriptado) {
            return base.Channel.GetValidaUsuarioAsync(usuario, passw, encriptado);
        }
        
        public CursosArsi.WebService.UsuarioEntity GetConfirmaUsuario(string usuario, string passw, bool encriptado) {
            return base.Channel.GetConfirmaUsuario(usuario, passw, encriptado);
        }
        
        public System.Threading.Tasks.Task<CursosArsi.WebService.UsuarioEntity> GetConfirmaUsuarioAsync(string usuario, string passw, bool encriptado) {
            return base.Channel.GetConfirmaUsuarioAsync(usuario, passw, encriptado);
        }
        
        public CursosArsi.WebService.DireccionEntity GetDatosDireccion(string codigoPostal) {
            return base.Channel.GetDatosDireccion(codigoPostal);
        }
        
        public System.Threading.Tasks.Task<CursosArsi.WebService.DireccionEntity> GetDatosDireccionAsync(string codigoPostal) {
            return base.Channel.GetDatosDireccionAsync(codigoPostal);
        }
        
        public string SetCambiaPassword(int idUsuario, string nvoPassword) {
            return base.Channel.SetCambiaPassword(idUsuario, nvoPassword);
        }
        
        public System.Threading.Tasks.Task<string> SetCambiaPasswordAsync(int idUsuario, string nvoPassword) {
            return base.Channel.SetCambiaPasswordAsync(idUsuario, nvoPassword);
        }
        
        public string SetRecuperaPassword(string eMail) {
            return base.Channel.SetRecuperaPassword(eMail);
        }
        
        public System.Threading.Tasks.Task<string> SetRecuperaPasswordAsync(string eMail) {
            return base.Channel.SetRecuperaPasswordAsync(eMail);
        }
        
        public CursosArsi.WebService.CategoriaEntity[] GetListaCategorias() {
            return base.Channel.GetListaCategorias();
        }
        
        public System.Threading.Tasks.Task<CursosArsi.WebService.CategoriaEntity[]> GetListaCategoriasAsync() {
            return base.Channel.GetListaCategoriasAsync();
        }
        
        public CursosArsi.WebService.CategoriaEntity[] GetListaCategoriasEmpresa(int idEmpresa) {
            return base.Channel.GetListaCategoriasEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<CursosArsi.WebService.CategoriaEntity[]> GetListaCategoriasEmpresaAsync(int idEmpresa) {
            return base.Channel.GetListaCategoriasEmpresaAsync(idEmpresa);
        }
        
        public bool SetRegistraProductoApp(CursosArsi.WebService.ProductoEntity producto) {
            return base.Channel.SetRegistraProductoApp(producto);
        }
        
        public System.Threading.Tasks.Task<bool> SetRegistraProductoAppAsync(CursosArsi.WebService.ProductoEntity producto) {
            return base.Channel.SetRegistraProductoAppAsync(producto);
        }
    }
}
